### ISSUE TITLE
Dockerfile path not found

### ISSUE THREAD

**Issue by frandorr** [FrontierDevelopmentLab/sat-extractor#23]
in gcp builder the dockerfile path is set to: `dockerfile_path = Path(__file__).parents[3]`
It returns `'/home/fran/miniconda3/envs/sat-extractor/lib/python3.9'`.

Should be changed to pass the path as parameter.

**Comment by frandorr** [comment]
It seems it is looking for a zip file, actually.

**Comment by carderne** [comment]
The idea for this was to allow other libraries to install `sat-extractor` and be able to build the docker image without being in the repo root. But I only got half-way there because obviously the Dockerfile won't be installed into `site-packages` by pip, so it doesn't work. I then started moving the `providers/` dir to be inside `src/satextractor/builder` (which might be a good idea long-term) but stopped there.

Will submit a PR reversing this for now.

**Comment by carderne** [comment]
https://github.com/FrontierDevelopmentLab/sat-extractor/pull/24
